### ISSUE TITLE
Adding new terrain

### ISSUE THREAD

**Issue by dderevjanik** [OpenRA/d2#85]
Hi,
I would like to ask how can I add new terrain type ? 
Is there any tutorial ? I already did terrain for RA (dessert) / Dune2k (cliff-to-sand)

For example, I tried to make sand-mountain

![image](https://user-images.githubusercontent.com/4524497/40237365-953d08bc-5ab0-11e8-815b-4d7a2af24841.png)

But now, I'm stucked with converting it to D2. I don't which palette use 

EDIT:
comparison with rock-mountain
![image](https://user-images.githubusercontent.com/4524497/40236604-67fe8f62-5aae-11e8-92e5-a23a15cd9c21.png)

**Comment by dderevjanik** [comment]
@pchote helped me to figure out how to add new terrain. 
First, I need to extract `ibm.pal` using utility.cmd inside d2 repo, to do it, run `utility.cmd` and type `--extract IBM.PAL`. `IBM.PAL` will be extracted to `engine/IBM.PAL`. 
After copy-pasting your bitmap terrain to shp builder, use `IBM.PAL` and save it to `mods/d2/bits` folder as `shp(ra)`. 
That's, now I have to add new entry to `mods/d2/tilesets/arrakis2.yml`. For example, I added 
```yml
	Template@200:
		Id: 200 # unique terrain ID
		Images: desert-cliff-01.shp # terrain shp
		Size: 1,1
		Categories: DuneRough # custom category, you have to define it at the start of file
		Tiles:
			0: Rough
```
